# Generated by Django 2.2.7 on 2019-12-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cars_capacity', models.IntegerField()),
                ('primary_atribute', models.CharField(max_length=30)),
            ],
        ),
    ]
