# Generated by Django 2.2.7 on 2019-12-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroes',
            name='cars_capacity',
        ),
        migrations.AddField(
            model_name='heroes',
            name='hero_img_url',
            field=models.CharField(default='burak', max_length=300),
            preserve_default=False,
        ),
    ]
